[package]
name = "turingarena-contest"
version = "0.1.0"
authors = ["Massimo Cairo <cairomassimo@gmail.com>"]
edition = "2018"

[dependencies]
juniper = "0.14.0"
juniper_rocket = "0.5.0"
rocket = "0.4.2"
diesel = { version = "1.4.2", features = ["sqlite"] }
rand = "0.7.2"
chrono = "0.4.9"
turingarena-contest-webcontent = { path = "../turingarena-contest-webcontent/" }
structopt = "~0.3.3"