name: CI testing
on: [push, pull_request_review]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm ci
      run: cd server/ && npm ci
    - name: npm run check
      run: cd server/ && npm run check
